### ISSUE TITLE
Add support for pulling and storing bundle content

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#12]
Update k8s bundle provisioner and add support for pulling and unpacking referenced bundle content.

**Comment by timflannagan** [comment]
@njhale We'll need to update the description of this at some point to detail any requirements for this component. IIRC, the only major one is that the pulling process needs to be done through CRI to be compatible with multi-arch images? Anything else?

**Comment by timflannagan** [comment]
#4 played around with using a singleton filesystem server for storing bundle contents as a tar file and making simple HTTP calls. We may want to investigate using https://github.com/warm-metal/csi-driver-image which Evan had shared a while back, or switch to using grpc unless the performance is negligible.

**Comment by joelanford** [comment]
> IIRC, the only major one is that the pulling process needs to be done through CRI to be compatible with multi-arch images?

Do we expect bundle images themselves to ever be arch-specific. They're just a pile of plaintext files, right?

Also, does the API need to expose a way for imagePullSecrets to be used (via a service account, direct specified secret names, or both)?

Lastly (probably not for MVP) do we want to make the image pull mechanism extensible? If there are tradeoffs between various choices (e.g. CRI requires spinning up a pod for every pull vs. github.com/google/go-containerregistry is super fast and in-process, but doesn't get cri-o mirror configurations) should we allow for this to be extensible?

**Comment by joelanford** [comment]
> could just fire off a goroutine that handles that process instead of a Job

I think sync vs async is a secondary question and a decision around that could be made separately:

With CRI-O, async looks like firing off a job and then re-reconciling. sync looks like firing off a job and then just waiting for it to complete (or fail), thus just blocking the reconciler.

With google/go-containerregistry, you're right that its essentially deciding how to do things in the background in the context of a reconciler. However this option would need to be handled with care. For example, what if I kill the controller process after a pull starts but before it finishes? What's keeping track of that between restarts of the operator?

--- 

I think the biggest motivation for using CRI is that it is essentially guaranteed to work the exact same way as images referenced in pod specs on the cluster. One example of where this is important is with CRI-O's mirrored registry support. Without a CSI driver (or a Job that populates some other accessible storage) that hooks into CRI, I don't see how we could support an pulling with the exact same configuration as the underlying CRI implementation.

**Comment by timflannagan** [comment]
@joelanford Right, and most provisioner implementations I have sitting locally fire off Jobs, set a top-level status field condition that marks the bundle unpacking process as in-progress, and exits early if the Job resource is in "pending" status. The controller would then be responsible for watching Job resources that are owned by that Bundle resource, so we ensure we're always working with the most up-to-date state.

Just thinking out loud: if we're interested in chasing down a CRI-based implementation for remote container images, we could still utilize the google/go-containerregistry library to check for container image digests to avoid re-pulling any image locally. The only clear downside with this approach, is that we wouldn't be able to utilize a local, on-disk bundle content cache for the provisioner container, as the Job resource is now responsible for pulling and unpacking to shared storage, unless we're using (and therefore requiring) a PVC to manage state between multiple containers. It seems like there are ways to circumvent that workflow: the bundle unpacking process the Job runs fires off GET/POST calls to some filesystem server that's deployed $somewhere. Any thoughts?

**Comment by timflannagan** [comment]
There's some good context that's been dumped in this ticket, but this ticket is already out-of-date now that the plain+v0 provisioner is starting to take shape. I'm going to close this out, but it would be nice to capture the want/need for being able to configure how Bundles are sourced, and whether we'd want to be able to provide knobs that allow the unpacking/sourcing process to happen in-process, e.g. using the g/go-containerregistry library, vs. managing an underlying Bundle unpack Pod.
