### ISSUE TITLE
Use an http server instead of pod logs for bundle unpacking

### ISSUE THREAD

**Issue by joelanford** [operator-framework/rukpak#153]
When unpacking a bundle, the current architecture launches a pod that reads a bundle's filesystem and writes a JSON map containing file paths and base64-encoded file content to the pod's log. Once it has completed writing the log, it exits.

This is simple and works fairly well, but it has several problems:
1. It requires a duplication of the bundle data on the node's disk. The bundle data is written once in the actual pod filesystem and another time in the pod log.
2. It is possible that the pod logs are eventually garbage collected for complete pods.

We can improve this by having the pod run a simple http server that serves a tar.gz of the bundle content. This solves both problems:
1. On each request it reads the pod filesystem to send the response, so no extra copies are written in the unpack pod
2. It serves the filesystem via http and is now running, thus completely avoiding the problem of pod log garbage collection.

In a follow-up, it might be worth considering another layer of optimization that removes the need for the intermediate configmaps. We can just have the bundle instance controller request the FS directly from the running pod.

**Comment by exdx** [comment]
Moving to backlog for now since it's unclear we will merge the implementation in #155.

**Comment by tylerslaton** [comment]
This is no longer relevant as the implementation of bundle unpacking has changed.
