### ISSUE TITLE
Support nested bundle directory structures

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#159]
The current iteration of the unpacker does not support nested directories -- if the file encountered by the `WalkDirFunc` is a directory, [it gets skipped](https://github.com/operator-framework/rukpak/blob/bb79ed5efd7e7c7a9c8ff5c83fdb10697ecee2a5/cmd/unpack/main.go#L33).

Therefore the contents of that directory do not get applied to the cluster. This is evident when unpacking the [combo manifests directory](https://github.com/operator-framework/combo/tree/main/manifests), where only 5 resources get unpacked (the ones at the top-level) and the CRD resources located in the crd subdirectory are not applied.  

Since git-backed bundle sources can have arbitrary directory structures, the unpacker should be able to fully unpack all manifests from a specified folder that has a nested directory structure.

**Comment by joelanford** [comment]
> if the file encountered by the WalkDirFunc is a directory, [it gets skipped](https://github.com/operator-framework/rukpak/blob/bb79ed5efd7e7c7a9c8ff5c83fdb10697ecee2a5/cmd/unpack/main.go#L33).

Returning `nil` early in the unpacker doesn't mean we don't walk the files in that directory. I'm fairly sure you'll see the combo CRDs in the unpacker log output.

However, the plain+v0 manifest reader specifically only reads the [manifests in the /manifests directory](https://github.com/operator-framework/rukpak/blob/3c6539db652ca020bfc47cc963070b27ce36c30a/internal/provisioner/plain/controllers/bundle_controller.go#L351), as per the (current, possibly underdefined) plain+v0 spec.

**Comment by exdx** [comment]
Oh ok, that makes more sense. In that case it should be more straightforward to implement support for nested directories by updating the manifest reader to read manifests from all the directories that exist?

**Comment by exdx** [comment]
I think this is a good thing to work on -- I would double check that this is still an issue, I know we refactored some of the relevant code recently. 

I believe we do want to support an arbitrary nested directory structure inside of the `/manifests` directory. In the plain bundle spec we mandated a flat directory but I would like to remove this requirement.

**Comment by timflannagan** [comment]
Can we enforce this behavior with an e2e test?

**Comment by akihikokuroda** [comment]
I'm thinking about adding the directories with a valid yaml file in it and an empty directory bundle in the e2e test.

**Comment by timflannagan** [comment]
> Can we enforce this behavior with an e2e test?

Ended up tracking this outside of this issue: https://github.com/operator-framework/rukpak/issues/195.

**Comment by timflannagan** [comment]
I'll throw you as the assignee for now but we should double check whether this is still an issue after some of the changes that have landed in the main branch recently.

**Comment by joelanford** [comment]
I thought we landed on not (yet at least) supporting nested directories because it could complicate semantics of orderly install/uninstall.

**Comment by akihikokuroda** [comment]
OK.  Do we can cancel this?

**Comment by exdx** [comment]
That's fair -- it's true we don't necessarily want to support this right away. I'm going to move this to the backlog for now.

**Comment by timflannagan** [comment]
I still think it's worth pursuing that e2e test if we're moving this ticket to the backlog. Maybe that's something you could tackle @akihikokuroda?

**Comment by akihikokuroda** [comment]
OK.  I'll do it.  Thanks!

**Comment by akihikokuroda** [comment]
One idea of ordering is that the order is reading each level alphabetically including the directory name.
For example, the root directory has files **a**, **c**, **e**, and **g** and a directory **d**.  The directory **d** has files **b** and **f**.   Then the order is **a,** **c**, **b**, **f**, **e**, **g**. 
I think this is easy to explain and implement.  WDYT?

**Comment by tylerslaton** [comment]
There are not currently any use cases for this issue so we're going to close this out. 

If in the future we want to reopen this because of a use case arising we should consider unwinding all of the nested manifests into a single directory for simplicity.
