### ISSUE TITLE
Generalize Bundle Image printcolumn for non-image based content sources

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#163]
Currently the printcolumn for a Bundle includes an `Image` field backed by the `spec.image` based on kubebuilder markers:
```
//+kubebuilder:printcolumn:name=Image,type=string,JSONPath=`.spec.image`
```
This works well for Bundles backed by an image, but results in a blank, empty column for non-image backed bundles.

As support is added for Bundles backed by additional content sources, this column should be generalized to output helpful reference information for the provided type of content. This custom column can be something generic like `Reference` and output different fields depending on the type of Bundle.  For example:
```
Type                                    Reference
Git-based bundle (tag)                  my-repo@v0.0.1
Git-based bundle (sha)                  my-repo@ae123xyz
Image-based bundle                      image:v0.0.1
```

**Comment by timflannagan** [comment]
Interesting - I knew this issue existed but I was also thinking of updating the IMAGE -> Reference custom column, and changing the status.Digest field to status.Reference which the bundle controller is responsible for propagating down the stack.

**Comment by timflannagan** [comment]
I was briefly playing around with this locally but I think we might run into some UX issues if we simply update that printer column to point to a status.Ref string that the bundle controller is responsible for populating, which might be fine but it's a change in behavior we've seen so far with a static spec.Image field implementation.

**Comment by timflannagan** [comment]
@joelanford @exdx any idea on whether this could be solved using a more complex jsonpath query? I wasn't able to get something sketched out when I tried but that could also be a short term win while we iron out the underlying UX.

**Comment by timflannagan** [comment]
Coming back to this again: I think we'd still run into this issue pushing through Joe's resolved source implementation in #191 if I'm reading the code correctly (and my brain isn't entirely dead for the day) where there's no guarantee that this field is set, especially in error paths, which is probably fine as long as we're all okay with the potential gap in UX. Maybe we can move the image custom column to -o wide output until we have a long term fix?

**Comment by exdx** [comment]
> Maybe we can move the image custom column to -o wide output until we have a long term fix?

I think that's reasonable. If we don't want to have a default value for this printer field, and we don't want it to come up empty, we can make it part of -o wide output for now.

**Comment by exdx** [comment]
Looking at this more today and it doesn't look like JSONPath supports conditional statements within one expression, so we couldn't do something like `spec.source.image.ref ? spec.source.image.ref : spec.source.git.repository` which I think was the intention.
