### ISSUE TITLE
Investigate metadata format for plain bundles

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#178]
As currently implemented plain bundles do not have associated with them any additional metadata: they are simply a collection of kubernetes manifest in a directory. There are however some explicit properties, such as schema version and bundle type, that can be useful to expose formally as part of a bundle. The plain provisioner can also read and act on this source of metadata. 

This issue is to investigate a good source of metadata for plain bundles that is useful and readily implementable. See #172 for an implementation and https://github.com/operator-framework/rukpak/pull/149#discussion_r834883731 for some background conversation on this issue. 

Once a metadata format becomes accepted, the plain bundle spec (added in #149) should also be updated to reflect the new format.

**Comment by timflannagan** [comment]
AC:
- Link a hackmd that does some initial spike investigation
- Create follow up ticket(s) as needed

**Comment by exdx** [comment]
See https://hackmd.io/Tk6uXGZ2SKqreteOUAF-NA for a draft metadata proposal

**Comment by exdx** [comment]
Closing as this spike work has largely been completed in the design doc linked above. I opened #242 as the follow-up implementation issue, put it in the backlog for now and we can triage it further in subsequent grooming meetings.
