### ISSUE TITLE
Introduce an e2e test for a BundleInstance that depends on another BundleInstance

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#183]
Goal: introduce a new BI e2e test that creates a BI that contains Bundle contents that rely on Bundle contents that don't exist on-cluster, then create a BI that contains those requisite resources, and waits until the original BI reports a successful state.

**Comment by joelanford** [comment]
The idea here is that we should keep retrying BIs that fail to rollout due to some missing prereq?

**Comment by timflannagan** [comment]
Yep that's what I had in mind - basically we're interested in eventually consistency here?
