### ISSUE TITLE
Consolidate deploy and release actions

### ISSUE THREAD

**Issue by joelanford** [operator-framework/rukpak#187]
We currently have two different actions in the repo that are responsible for pushing docker images:
1. `.github/workflows/deploy.yaml` builds and pushes `quay.io/operator-framework/plain-provisioner:main`
2. `.github/workflows/release.yaml` builds and pushes `quay.io/operator-framework/plain-provisioner:<tag>`

We should consolidate these so that there is only workflow responsible for pushing all image artifacts from this repo.

**Acceptance Criteria:**
 - only a single gha for building and pushing all image artefacts from this repo

**Comment by timflannagan** [comment]
@joelanford did you want to take this ticket and assign yourself?

**Comment by timflannagan** [comment]
I took a stab at this in #225
