### ISSUE TITLE
Introduce caching to the GHA workflows

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#194]
Goal: speed up the GHA workflows by caching the rukpak-related binaries between workflow runs.

**Comment by timflannagan** [comment]
We should be able to get away with just caching the build/package cache for the rukpak executables, but it would also be nice to cache the tooling related executables which help influence the overall CI runtime.

**Comment by joelanford** [comment]
A good chunk of the tooling executables are built with `go build` so they should benefit from the same caching that the rukpak executables use.

**Comment by timflannagan** [comment]
It's a real shame I haven't been able to figure out how to get https://github.com/nektos/act to work with docker-related (maybe I'm making the premature assumption we're consolidating build/container processes) jobs/workflows/etc. but it would be super easy to iterate on that kind of effort using that tooling.

**Comment by timflannagan** [comment]
Looking at the latest set of actions it doesn't seem like we're really running into issues with long PR feedback so I'm going to move this back to 0.4, or until this becomes more a pain point in the short term.

**Comment by tylerslaton** [comment]
The gains here are pretty negligible and the E2E feedback is already fairly quick. Closing this out until it becomes something we really need.
