### ISSUE TITLE
Investigate how to expose package metadata for the plain manifest bundle format

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#23]
The static k8s bundle format is currently defined as a series of static YAML manifests that are wrapped in a scratch container image that get unpacked and stored at runtime. Right now, that implementation has no way of explicitly exposing metadata, like the current package version, the default channel, or any dependencies that come with this package. Exposing that same kind of metadata at the Bundle-level (vs. the package level) may be challenging for gitops workflows, and defining an optional metadata file that gets packaged with the static k8s bundle format could be a decent way to expose those knobs.

**Comment by joelanford** [comment]
We definitely don't want to carry forward the package and channel-level metadata fields (channels, default channel).

I think we will need metadata though (schema: "plain+v1", package name, bundle version).

The registry+v1 bundle also has scorecard and metrics metadata, which we'll need to consider.

**Comment by exdx** [comment]
This seems like a dupe of #178 which was closed since we have https://hackmd.io/Tk6uXGZ2SKqreteOUAF-NA now and a follow-up implementation issue in #242. Should we close this one out as well?

**Comment by timflannagan** [comment]
Yep this looks like a duplicate - closing this out.
