### ISSUE TITLE
Ensure original unpacked bundle content is always being referenced

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#255]
There is a scenario where a Bundle backed by an image tag is unpacked successfully to the cluster, the Bundle is re-reconciled (for example, a label has changed), and at the same time the SHA of the underlying image has changed, pointing to different content. In that case, the Bundle should not be updated to reflect external changes. 

This may be an additional e2e test that verifies this behavior, or documentation that highlights that the behavior of the Bundle is similar to that of a Pod when it comes to updating the contents of the Pod -- it does not update them by default.

**Comment by tylerslaton** [comment]
Closing this issue out as it is no longer an issue with changes to our Bundle unpacking approach.
