### ISSUE TITLE
Add admission webhook for bundle immutability

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#256]
This issue describes the desire to incorporate a webhook as part of the core rukpak APIs that would make bundles immutable, meaning a Bundle cannot be edited after it is created. This is desirable as part of the embedded Bundle in the BundleInstance feature, since a user may inadvertently try to change the Bundle that was created from the embedded Bundle in the BI instead of changing the BI itself, which is the intention. 

An immutable bundle is intuitive from a general standpoint, as it represents a snapshot of some desired content, and cannot be altered -- the recommended workflow is to delete/recreate the Bundle. 

Since there is no way in Kuberentes to mark a spec as immutable, this will need to be implemented via a validating webhook that watches for Bundle update/patch/put events and denies them.

**Comment by timflannagan** [comment]
@joelanford @exdx Should we move bump up the priority for Bundle immutability, and place this issue in the 0.4 milestone? With higher level concepts coming into play, e.g. embedded bundles, pivoting mechanisms used under-the-hood, etc.

**Comment by timflannagan** [comment]
Implemented and closed in #286. Related to #288.
