### ISSUE TITLE
Update Go version to 1.18

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#262]
Goal: update the Go version used throughout the repository to Go 1.18.

AC:
- Update the root go.mod
- Update the GHA workflows to use Go 1.18
- Update any Makefile/script references to Go 1.17

**Comment by joelanford** [comment]
Might need to bump golangci-lint version as well.

**Comment by EdwinWalela** [comment]
@timflannagan I'd like to take this up

**Comment by timflannagan** [comment]
@EdwinWalela Awesome - added you as the assignee.
