### ISSUE TITLE
Add support for deploying rukpak on OperatorHub.io

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#273]
Goal: enable users to deploy the rukpak stack on https://operatorhub.io/.

AC:
- Follow the onboarding instructions detailed in https://operatorhub.io/contribute

**Comment by timflannagan** [comment]
This seems like a solid 0.5 candidate.

cc @joelanford @perdasilva

**Comment by exdx** [comment]
Discussed this a bit with @kevinrizza, it was not entirely clear whether this would be a big benefit. 

- Downstream users of rukpak on openshift would probably see it be installed via CVO manifests
- Upstream users could install it the way they do currently, by applying the raw manifests

There is some potential gain in discoverability for the project if its on operatorhub, but its not super clear if its worth the effort. 

Also, if any code in the project has to change to fit OLM's packaging model, then it would probably be a reason not to integrate it with OLM.  Not code to create the OLM bundle itself, but code around the API design and other conventions of rukpak.

**Comment by njhale** [comment]
A discussion in the rukpak grooming session resulted in us deciding to close this due to a lack of perceived value.
