### ISSUE TITLE
Support private git source bundle

### ISSUE THREAD

**Issue by akihikokuroda** [operator-framework/rukpak#285]
https://github.com/operator-framework/rukpak/issues/81 addressed the image bundle in a private registry.  The git source can also be in a private git repository.

**Comment by timflannagan** [comment]
I wonder whether it makes sense to just have something closer to a top-level spec.Secret(s) field for configuring any of the bundle source type authorization needs.

**Comment by akihikokuroda** [comment]
I'm not sure about it.  Each source may have different type of authorization information.  Putting the authorization information in each BundleSource may be better for extendability.

**Comment by akihikokuroda** [comment]
On second thoughts, the bundle probably needs to have one secret name for any source type.  The contents of the secret may be different for each source.  It may be good idea to have the top-level spec.Secret.

**Comment by joelanford** [comment]
I think I actually lean more toward putting the auth concerns in the specific source types. I just have a feeling that we'll have problems in both directions:
1. We'll have sources that have auth concerns specific to that source.
2. We'll have general auth fields that don't apply to some sources.

If we keep things within each source type struct, we'll be able to organically grow auth stuff without worrying about how well it generalizes.

**Comment by akihikokuroda** [comment]
Okey.  I'll update #287 to have the authorization information in each source type.  It probably makes sense to have all the information for the source in one place.

**Comment by timflannagan** [comment]
Yep I'm fine with that in the short term, and can revisit whether this in the API structure we'd want/need further down the line once we get more concrete use cases come down the pipeline.

**Comment by timflannagan** [comment]
@akihikokuroda Do we want to throw this in the 0.4 or 0.5 milestone? I think we'll cut 0.4 in like two weekish, so there is a good chunk of runway still remaining.

**Comment by timflannagan** [comment]
(actually I'll just throw it in the 0.4 milestone as the implementation should be fairly straight forward)

**Comment by exdx** [comment]
This depends on #366 so we will move over to the v0.6.0 milestone.
