### ISSUE TITLE
Introduce metrics framework for tracking test/pass CI failure rates

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#306]
Goal: introduce metrics that outline CI's pass/fail rates over time to avoid getting into the same situation as OLM's e2e suite.

**Comment by timflannagan** [comment]
(this was suggested by @njhale during yesterday's grooming - throwing this in the backlog right now as we're still in the iteration phase)

**Comment by exdx** [comment]
Definitely a nice to have. I wonder if there is an off the shelf solution for this. 

Question from grooming: what is the goal of this framework? Is it just to identify flakes.
