### ISSUE TITLE
Update the hash-based implementation for the plain provisioner's BI controller

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#334]
Follow-up to the comment in https://github.com/operator-framework/rukpak/pull/293#discussion_r865173446 which suggested we explore the usage of hashing the BundleTemplate spec.Template field and using that hash value as the generated Bundle's metadata.Name.

**Comment by exdx** [comment]
Note: if we wanted to follow the ReplicaSet hasher's implementation here https://github.com/kubernetes/kubernetes/blob/313d9fb0b12ef627644bf2a7153bd1fd8dc399fd/pkg/controller/controller_utils.go#L1155 we would need to add a `CollisionCount` field on the status of the BI to avoid potential collisions, like they did on the DaemonSetStatus. I'm not sure this is entirely necessary for a first pass of this feature.
