### ISSUE TITLE
Add initial scaffolding for rukpakctl

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#369]
`rukpakctl` is a new CLI tool that interacts with rukpak resources. See [the design doc](https://hackmd.io/AJ8ygfzbTrmXv_CIiUCPtQ?view) for a more detailed document outlining the tool. This issue is for adding the baseline code necessary to add the binary to the project. 

A/C:
* Add new folder and main.go under /cmd
* Bootstrap a cobra CLI tool in the new folder
* Add Makefile targets

**Comment by akihikokuroda** [comment]
I would like to try this.
