### ISSUE TITLE
Update e2e tests to use images stored in the image registry

### ISSUE THREAD

**Issue by akihikokuroda** [operator-framework/rukpak#381]
Image registry for e2e tests are added in #346.  It enables tests of [authorization function of the image registry access](https://github.com/operator-framework/rukpak/pull/279). Some bundle tests should use the image registry.

**Comment by akihikokuroda** [comment]
This depends on #280

**Comment by timflannagan** [comment]
Follow-up to #280 which add support for deploying an in-cluster image registry, which will store the e2e testdata container images. This issue is centered around updating the e2e suite to reference those images stored in that deployed, in-cluster registry.
