### ISSUE TITLE
Investigate hash digest inconsistency 

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#423]
The implemented hashing algorithm for determining the names of Bundles added in #377 seems to produce different results whether on macOS or Linux. Unit tests that checked the Bundle name against a precomputed hash were removed, but can be a source to investigate why a hash of a BundleTemplate seems to produce different results on different OSs. 
Some notes:
* This implementation is directly from OLM and also used by core kubernetes for computing the pod-template-hash
* The results were non-determnistic whether hashing a `*BundleTemplate` or a concrete `BundleTemplate`

**Comment by exdx** [comment]
The hash also seems to change between kube versions? See https://github.com/operator-framework/rukpak/runs/6782303088?check_suite_focus=true

**Comment by exdx** [comment]
See https://github.com/nsapse/template_hash_test for a base case test which runs the hash implementation. On both macOS and Linux, the results were consistent. 

```
hash output (template): 85887ff7f7
hash output (pointer): 54dd864b69
```

**Comment by jmrodri** [comment]
> See https://github.com/nsapse/template_hash_test for a base case test which runs the hash implementation. On both macOS and Linux, the results were consistent.
> 
> ```
> hash output (template): 85887ff7f7
> hash output (pointer): 54dd864b69
> ```

@exdx so when you state "the results were consistent", does that mean that you got the same hash on both macOS and Linux? Or does that mean that you were able to recreate the original failure thus "the results were consistent" with the original error?

**Comment by jmrodri** [comment]
I ran the above test in github actions on ubuntu and macos12. The results were exactly the same as @exdx found in this comment: https://github.com/operator-framework/rukpak/issues/423#issuecomment-1151587380

Here is the macos result, for full results see https://github.com/jmrodri/template_hash_test/runs/7780120916?check_suite_focus=true:

```
go version: "go1.18.5", GOOS: "darwin", GOARCH: "amd64"
hash output (template): 85887ff7f7
hash output (pointer): 54dd864b69
```

Here is the linux result, for full results see https://github.com/jmrodri/template_hash_test/runs/7780120860?check_suite_focus=true:
```
go version: "go1.18.5", GOOS: "linux", GOARCH: "amd64"
hash output (template): 85887ff7f7
hash output (pointer): 54dd864b69
```

**Comment by jmrodri** [comment]
I am of the opinion that this is not an issue. We have tried on several OSes and arches with the same consistent result, I suspect if we did see an inconsistent number, that it might have been an actual difference.
