### ISSUE TITLE
Add e2e tests for the content http server of the plain provisioner

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#427]
Add e2e tests that exercise the content http server of the plain provisioner (including authorization via kube-rbac-proxy).

Follow-up work from #311

**Comment by joelanford** [comment]
Do you think a sufficient test would be to setup a bundle instance where:
1. the BI provisioner is plain
2. the Bundle provisioner is registry

In that scenario, the registry provisioner stores that bundle locally, so when the plain BI controller goes to load it, it has to use the fallback http source to fetch it from the registry provisioner. 

What that actually tests is:
1. the plain provisioner can successfully act as a client to fetch bundles from remote provisioner http servers
2. the registry provisioner can successfully act as a server to serve bundles to remote clients.

... which i guess is not what this issue states. It wants to test that the plain provisioner can serve its bundles.
