### ISSUE TITLE
Add links to the rukpak one pager hackmd design documentation

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#441]
Goal: Ensure devs/users can discover design documentation over time.

Right now most of the design (e.g. one pagers) documentation is hosted on a rukpak team hackmd. It might be worth surfacing that public link somewhere in the short term.

**Comment by exdx** [comment]
I'm not sure you can link to the rukpak team notes directly -- if I try on a private browser session, I get a 403.

Does this imply we should provide direct links to each public note?

**Comment by timflannagan** [comment]
Does it make sense to have those one pagers live in-tree for this repository then? Those designs should be public facing anyways.

**Comment by exdx** [comment]
I opened a PR which compromises: it includes a link to all the HackMD documentation. 

Copying it and having it live in tree is an alternative, but this approach is less toil and just as useful.
