### ISSUE TITLE
When a bundle fails to unpack, the reason should be surfaced in bundleDeployment

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#444]
Goal: Re-visit the UX around the HasValidBundle and Installed types, and the printer columns.

The BundleDeployment controllers first try to unpack the desired bundle source before applying those unpacked source manifests. In the case that the desired bundle fails to unpack, the provisioner implementations surface a HasValidBundle status conditions type. When querying for BundleDeployment status locally, the "INSTALL STATE" printer column UX is empty which doesn't properly relay the current state.

**Comment by timflannagan** [comment]
I think I'm slightly more interested in the underlying status conditions vs. the printer column UX, at least for now. What does the YAML output of that underlying `fail` BundleDeployment resource look like?

**Comment by akihikokuroda** [comment]
They are:
```
apiVersion: v1
items:
- apiVersion: core.rukpak.io/v1alpha1
  kind: BundleDeployment
  metadata:
    creationTimestamp: "2022-07-08T13:42:46Z"
    generation: 1
    name: fail
    resourceVersion: "1132"
    uid: 552541ff-a32b-402a-9b0d-ae4ee7f70c83
  spec:
    provisionerClassName: core.rukpak.io/plain
    template:
      metadata: {}
      spec:
        provisionerClassName: core.rukpak.io/plain
        source:
          local:
            configMap:
              name: failc7knd
              namespace: default
          type: local
  status:
    activeBundle: fail-6b974bf987
    conditions:
    - lastTransitionTime: "2022-07-08T13:42:46Z"
      message: Failed to unpack the fail-6b974bf987 Bundle
      reason: UnpackFailed
      status: "False"
      type: HasValidBundle
- apiVersion: core.rukpak.io/v1alpha1
  kind: BundleDeployment
  metadata:
    creationTimestamp: "2022-07-08T13:43:40Z"
    generation: 1
    name: valid
    resourceVersion: "1259"
    uid: 8669d3f0-f01f-455f-b10f-bd07c4addeeb
  spec:
    provisionerClassName: core.rukpak.io/plain
    template:
      metadata: {}
      spec:
        provisionerClassName: core.rukpak.io/plain
        source:
          local:
            configMap:
              name: validhnmdv
              namespace: default
          type: local
  status:
    activeBundle: valid-8594776745
    conditions:
    - lastTransitionTime: "2022-07-08T13:43:40Z"
      message: Successfully unpacked the valid-8594776745 Bundle
      reason: UnpackSuccessful
      status: "True"
      type: HasValidBundle
    - lastTransitionTime: "2022-07-08T13:43:45Z"
      message: instantiated bundle valid-8594776745 successfully
      reason: InstallationSucceeded
      status: "True"
      type: Installed
kind: List
metadata:
  resourceVersion: ""

```

**Comment by timflannagan** [comment]
Given the plain provisioner knows which bundle needs to exist at any point in time, and we already check for whether that "active" bundle is reporting an unpacked phase yet, I think we can extend that logic to ensure we're propagating a more reasonable condition message and/or reason:

```yaml
...
  status:
    activeBundle: fail-6b974bf987
    conditions:
    - lastTransitionTime: "2022-07-08T13:42:46Z"
      message: Failed to unpack the fail-6b974bf987 Bundle
      reason: UnpackFailed
      status: "False"
      type: HasValidBundle
```

Here, the "Failed to unpack the .... Bundle" would require me to GET that bundle's metadata.Name, and inspect it further for why it failed. I was suggesting that we should be propagating that information back to the BundleDeployment status instead to reduce the number of manual steps for invalid bundles. Thoughts?

**Comment by akihikokuroda** [comment]
Here is the status in the bundle.
```
  status:
    conditions:
    - lastTransitionTime: "2022-07-08T13:42:46Z"
      message: 'get objects from bundle manifests: read ".gitignore": error unmarshaling
        JSON: while decoding JSON: json: cannot unmarshal string into Go value of
        type map[string]interface {}'
      reason: UnpackFailed
      status: "False"
      type: Unpacked
```
There are some options:
1. append the bundle condition message to the bundledeplpyment condition message.
2. add the `BundleConditions` in the BundleDeploymentStatus and copy the bundle conditions into it
3. add a new bundledeplpyment condition type `BundleConditionUnpacked` and put the bundle unpack condition into the bundledeployment condition.

We still need to have the bundle name somewhere in the BundleDeploymentStatus.  We may need to rename the `activeBundle` to just `bundle` and have another field `bundleStatus` to hold the status of the bundle.

**Comment by timflannagan** [comment]
> We still need to have the bundle name somewhere in the BundleDeploymentStatus

Hmm. Do we have an existing issue for this? I'd guess I need to see explicit use cases for why we'd need an explicit status field for the "active" bundle's metadata. What we can do in the short term is wrap that "Failed to unpack the fail-6b974bf987 Bundle: ..." with the underlying Bundle's message to still encode that "active" Bundle identifier in the status $somewhere.

**Comment by akihikokuroda** [comment]
OK.  We can reformat the `HasValidBundle` condition message to include the bundle `Unpacked` condition message and the bundle name when unpack failed.
Is it enough for this issue?  Do we need the print column change, too?
