### ISSUE TITLE
Introduce a helm chart provisioner

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/rukpak#460]
## Requirement

That should be great to have a provisioner able to install/uninstall/upgrade a helm chart and that we have also the possibility to pass the values.yaml (key/values pairs to customize the helm template resource files). That will certainly imply that we design something like (Helm tiller) to perform the rendering of the chart into k8s resources during the installation

**Comment by timflannagan** [comment]
Yep, a helm provisioner seems like a solid candidate for the next provisioner implementation, but I imagine the priority is low for the directly OLM team in the short term while we continue to iterate on layers that build on top of rukpak primitives.

We've briefly floated around the idea of prototyping a helm provisioner, which has it's own class of potential problems:

- How do we expose the values.yaml in a way that rukpak's BundleDeployment API can consume them?
- Would it be possible to have a provisioner implementation that sources helm charts, and "converts" (e.g. renders those charts + values.yaml) that bundle format into a "plain bundle" format?

That conversion logic is something we have already pursued w.r.t the registry+v1 provisioner, which translates OLM's legacy registry+v1 bundle format into a "plain bundle" format, so there's already precedence for that runtime design. And the benefit there is that we only need to bootstrap a controller that watches the rukpak Bundle resource, converts the bundle format into a plain bundle format, and stores that bundle format in it's in-memory store.

Thoughts @joelanford?

**Comment by timflannagan** [comment]
Moving this to the backlog for now, and we can re-groom later. Another related issue may be #425 as a helm provisioner may not be a core rukpak provisioner (if there's even core rukpak provisioners that ship from this repository longer term), and may live out-of-tree going forward.

**Comment by cmoulliard** [comment]
> * How do we expose the values.yaml in a way that rukpak's BundleDeployment API can consume them?

They could be passed simply using a ConfigMap.

**Comment by cmoulliard** [comment]
> * Would it be possible to have a provisioner implementation that sources helm charts, and "converts" (e.g. renders those charts + values.yaml) that bundle format into a "plain bundle" format?

I would like a lot that the provisioner is able to render the templates using a template engine + values passed. This is what carvel kapp controller do - https://carvel.dev/kapp-controller/docs/v0.38.0/app-examples/#gitops-with-a-helm-chart

**Comment by timflannagan** [comment]
> They could be passed simply using a ConfigMap.

Yeah, definitely, and I think this is sufficient for a prototype's implementation of a helm provisioner, especially since bridging the gap between communities that use helm today, and want to simply point OLM to a helm chart in a first-class way (e.g. no hybrid model), seems worth chasing.

_But_ we may want to enable admins to configure BundleDeployment in a generic way, and maybe a helm/kustomize provisioner can hook into that generic configuration mechanism, which will help enable admins to adjust bundle contents before creating them (e.g. hot fix mechanism).

**Comment by timflannagan** [comment]
Another thing that we may want to consider is where to find a helm chart source. Does a provisioner implementation need to extend to sourcing helm charts from https://artifacthub.io/, or is the existing supported set of image/git/configmap source types sufficient here?

**Comment by timflannagan** [comment]
Yeah, a generic HTTP source seems reasonable to me.

**Comment by akihikokuroda** [comment]
@timflannagan I would try.  This is interesting one.  Thanks!

**Comment by timflannagan** [comment]
@akihikokuroda I think we'll likely want a one pager design document here so we're all on the same page given we may need to touch the BD API surface. Thoughts?

**Comment by exdx** [comment]
Yes, good idea on the doc.

Added to the current milestone.

**Comment by akihikokuroda** [comment]
# Helm provisioner

## API changes

### BundleDeployment

`Config runtime.RawExtension json:"config,omitempty"`

is added to hold provisioner specific configurations.

```
// BundleDeploymentSpec defines the desired state of BundleDeployment
type BundleDeploymentSpec struct {
	// ProvisionerClassName sets the name of the provisioner that should reconcile this BundleDeployment.
	ProvisionerClassName string `json:"provisionerClassName"`
	// Template describes the generated Bundle that this deployment will manage.
	Template *BundleTemplate `json:"template"`
	// Config is provisioner specific configurations
	// +kubebuilder:pruning:PreserveUnknownFields
	Config runtime.RawExtension `json:"config,omitempty"`
}
```
For the Helm provisioner, the `Config` is used for providing the values.yaml file via a ConfigMap.

```
  config:
    valuesFrom:
      configMapName: values
```
The ConfigMap specified in the `config` have to have a `values.yaml` key and the contents of the values.yaml file as the data in the Data.
It can be create by
```
kubectl create configmap --from-file=values.yaml
```
### Bundle

A new source type `HelmSource` is added to the `BundleSource`. It holds a helm repository URL, a chart name and an optional chart version. 
```
type HelmSource struct {
	// Repository is a URL link to the Helm repository containing the chart for the bundle.
	// Repository is required and the URL should be parsable by a standard git tool.
	Repository string `json:"repository"`
	// ChartName refers to the chart name for the bundle within the helm repository.
	ChartName string `json:"name"`
	// ChartVersion refers to the chart version for the bundle within the helm repository.
	// ChartVersion is optional
	ChartVersion string `json:"version,omitempty"`
}
```

There are some options not to add the helm provisioner specific source in the BundleSource.

1. Create a generic source type with `runtime.RawExtension` type.
2. Create a HTTP source type with an URL that the helm provisioner parases it to extract necessary information.

## Implementation

Helm chars are downloaded from registories using `helm.sh/helm/v3` packages by the bundle controller. The downloaded chart is stored in the `storage` as-is format (tgz) without parsing.  The bundledeployment controller installs the chart using`github.com/operator-framework/helm-operator-plugins/pkg/client` which is also using `helm.sh/helm/v3` internally.  It applies the values in the specified ConfigMap at instll.

**Comment by akihikokuroda** [comment]
@exdx @timflannagan @joelanford Here it is.

**Comment by joelanford** [comment]
`HelmSource` is an interesting approach I hadn't thought too much about. Maybe we could start with a generic http(s) source and see how far the gets us? I feel like that'll _just work_ for helm charts and it'll work for arbitrary other bundle formats as well. After all, a helm repo is just a webserver that hosts tar.gz file and some extra index metadata about the charts in that repo. Since we're just after a specific chart, it seems like users could pretty easily reference a helm chart by its full URL.

For example:
```yaml
helm:
  repository: https://kubernetes.github.io/ingress-nginx
  chartName: ingress-nginx
  chartVersion: 4.2.0
```
would be the same as
```yaml
http:
  url: https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.2.0/ingress-nginx-4.2.0.tgz
```

The benefit of the former option is that you don't have to do the extra step of looking up the chart url from the repo index.

**Comment by akihikokuroda** [comment]
OK.  I'll make changes.  I think that the helm source may be useful to support the OCI registry.  I guess that it may not be popular yet so I'll start with the generic http first.

**Comment by joelanford** [comment]
> helm source may be useful to support the OCI registry

I wonder if our existing `image` source would already cover that?

**Comment by joelanford** [comment]
> Is it better to have Auth to support basic access authentication?

Could re-use the http pieces of the auth struct that we use for the git source?

**Comment by akihikokuroda** [comment]
Yes, it can.  I was thinking about it.

**Comment by akihikokuroda** [comment]
> I wonder if our existing image source would already cover that?
I'm not sure.  I'll take a look.

**Comment by timflannagan** [comment]
(updating the issue title for better signal in the release notes)

/retitle Introduce a helm chart provisioner

**Comment by cmoulliard** [comment]
> OK. I'll make changes. I think that the helm source may be useful to support the OCI registry. I guess that it may not be popular yet so I'll start with the generic http first.

Such a feature is only available since helm 3.8 - https://helm.sh/docs/topics/registries/

**Comment by cmoulliard** [comment]
Have you added to the project an example and extended the documentation to use the Helm provisioner ?

**Comment by timflannagan** [comment]
@cmoulliard It looks like @akihikokuroda had added some documentation in #473, and a guide that runs through some examples in https://github.com/operator-framework/rukpak/tree/main/internal/provisioner/helm. We merged the initial implementation earlier this week, so cleaning up any docs, providing more examples, etc. would be a good exercise.
