### ISSUE TITLE
Long name bundledeployment creation fails bundle creation

### ISSUE THREAD

**Issue by akihikokuroda** [operator-framework/rukpak#485]
When creating a bundledeployment with a long name, the bundledeployment instance is created but the bundle instance creation fails.  Here is the status of the bundledeployment
```
status:
    conditions:
    - lastTransitionTime: "2022-08-09T18:00:52Z"
      message: 'Bundle.core.rukpak.io "my-ahoy-thisisalongnamethatexceedthelimit-84fc8bfc6f"
        is invalid: metadata.name: Too long: may not be longer than 40'
      reason: ReconcileFailed
      status: Unknown
      type: HasValidBundle
```

**Comment by akihikokuroda** [comment]
Currently: 

len(bundle name) == len(bundledeplyment name) + 11
len(unpack pod name) == len(bundle name) + 14

Should we limit the length of the bundledeoloyment name up to 29?

**Comment by joelanford** [comment]
1. It seems like we probably _do_ want a bundledeployment name length validation
2. Perhaps we make the bundle hash suffix from the BD shorter (e.g. `-<6-hex-digits>` rather than the current 10)?
3. Perhaps we make the unpack pod name == the bundle name (rather than add extra prefixes/suffixes) to allow the BD name to be as long as possible.

**Comment by akihikokuroda** [comment]
@joelanford All items make sense to me.

The 2. is a little difficult to shorten the hash value.  We can reduce (probably just one or two letters) the string length by converting the hash value to hex earlier.
  
` rand.SafeEncodeString(fmt.Sprint(hasher.Sum32()))` -> ` rand.SafeEncodeString(fmt.Sprintf("%x", hasher.Sum32()))`

How long would the max length of the BD be?  like 50?  WDYT?

**Comment by akihikokuroda** [comment]
OK.  The hash can be truncated to 6 letters.

**Comment by timflannagan** [comment]
Should we update this issue name so there's more signal in the upcoming release notes?
