### ISSUE TITLE
The helm chart provisioner doesn't trigger a new reconciliation after updating the spec.config field

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#504]
After deploying rukpak using the main branch images, and creating a BundleDeployment that specifies the helm chart provisioner's unique ID with an empty spec.config configuration, the result is a successful installation of the helm example application. When updating that BundleDeployment resource on the cluster, and then adding the spec.config configuration, it appears that the helm chart provisioner is able to validate the contents of those fields, but I didn't see any obvious changes in the status that would express those changes were persisted in the cluster.

**Comment by akihikokuroda** [comment]
How can the status express the change?  Is it OK just change the last transition time? @timflannagan

**Comment by timflannagan** [comment]
@akihikokuroda I haven't put a ton of thought into the UX here. What I had initially in mind was that we'd update the logic that checks the bundle template logic, and extend that to also check the spec.config skew. But I'm not sure if that's sufficient from an end user's perspective.

**Comment by akihikokuroda** [comment]
@timflannagan It actually reconciles when the contents of the config is changed.  It just doesn't express the fact that the reconcile happens.  The upgrade finishes within one reconcile it can not update the `ReasonInstallationSucceeded` condition entry.

**Comment by joelanford** [comment]
>  Is it OK just changing the last transition time?

No, last transition time should only ever change if the `Status` of the condition changes.

I think the more appropriate thing to do here is add a `status.observedGeneration` field on the BD. That way, even if a spec update doesn't actually result in any change to the managed objects, there's still a signal on the BD that we reconciled.
