### ISSUE TITLE
Skip the .helmignore file when walking the chart directory

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#505]
It looks like helm has a [.helmignore file](https://helm.sh/docs/chart_template_guide/helm_ignore_file/) that could be skipped (and potentially it's contents) when walking the chart directory in the helm chart's bundle deployment controller.

**Comment by joelanford** [comment]
I assume the helm libraries we use to load the dir into a chart object handle this for us. Is there a specific issue you've run into?

**Comment by joelanford** [comment]
Ah! I se that we're implementing the fs Walk ourselves. I've replaced that implementation with one that uses Helm's `LoadArchive` in #516, which means basically all of our chart loading/parsing logic is done by Helm, not us.
