### ISSUE TITLE
Consider adding a Pod watch for the helm chart bundle controller

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#510]
The helm chart bundle controller should in theory be able to support git-based source types along with the http sources. The former unpacks git repository contents via an asynchronous Pod, so setting up a watch based on that unpack Pod could help insulate failure states better.

**Comment by akihikokuroda** [comment]
The git source unpacker is no longer using the asynchronous Pod.  It's using `github.com/go-git/go-git` package.

**Comment by timflannagan** [comment]
@akihikokuroda Nice catch. What about container images here then? I feel like we'd be able to consume a container image that wraps a helm chart in it's current form.

**Comment by akihikokuroda** [comment]
That's true.  I guess it's very rare use case, though.

**Comment by timflannagan** [comment]
/retitle Consider adding a Pod watch for the helm chart bundle controller

**Comment by timflannagan** [comment]
I think we can let this sit in ice in the short term then. Maybe use cases will appear over time where container images need to be used here.

**Comment by joelanford** [comment]
Helm supports charts as OCI images as of 3.8.0: https://helm.sh/docs/topics/registries/

I think we should up the priority, especially considering this should be fairly straightforward?

**Comment by timflannagan** [comment]
/retitle Add a Pod watcher to the helm provisioner bundle controller
