### ISSUE TITLE
Separate source docs from bundle format docs

### ISSUE THREAD

**Issue by joelanford** [operator-framework/rukpak#522]
Today in the [plain bundle spec](https://github.com/operator-framework/rukpak/blob/main/docs/plain-bundle-spec.md), we talk about sourcing details unrelated to the actual spec of the plain bundle format. For example, the "Technical Details" section talks about images vs git repos.

I think we've intentionally defined a separation between sourcing a bundle and parsing a bundle that we should reflect in our documentation.

IMO, we should re-organize our docs such that we have something along the lines of:

```console
docs
├── bundles
│   ├── helm.md
│   ├── plain.md
│   └── registry.md
├── provisioners
│   ├── helm.md
│   ├── plain.md
│   └── registry.md
└── sources
    ├── git.md
    ├── http.md
    ├── image.md
    ├── local.md
    └── upload.md
```

Where:
- Bundle specs do not mention source implementations
- Source docs do not mention bundle specs
- Provisioner docs link to sources/bundle docs as necessary to explain what they support.

**Comment by akihikokuroda** [comment]
I wonder if it's better to have a provisioners.md file in the docs/provisioners and point to the README.mds in each internal/provisioner/xxxxxx.
