### ISSUE TITLE
Build rukpak images for multiple architectures

### ISSUE THREAD

**Issue by joelanford** [operator-framework/rukpak#53]
It'd be great to go ahead and setup multi-arch image builds. It will help us avoid (or at least be more mindful about) changes that break multi-arch image builds (e.g. accidental reliance on CGO)

Possible tools to use:
- https://github.com/marketplace/actions/docker-buildx-bake
- https://goreleaser.com/

References:
 - operator-lifecycle-manager [release job](https://github.com/openshift/operator-framework-olm/blob/master/staging/operator-lifecycle-manager/.goreleaser.yml)

**Acceptance Criteria:**
- release jobs for: amd64, ppc64Ie, s390x, arm64 architectures
- ensure compilation, environment docker images are updated
- binaries of all architectures go through the pipeline (get tested, etc.)

**Comment by timflannagan** [comment]
Does this need to be a 0.0.1 release blocker?

**Comment by joelanford** [comment]
not in my opinion

**Comment by exdx** [comment]
0.3 candidate
