### ISSUE TITLE
Use CI-built images for e2e tests

### ISSUE THREAD

**Issue by joelanford** [operator-framework/rukpak#55]
Not sure we've progressed far enough for this to be relevant right now, but we should structure our CI such that:
1. We build all images in the repo.
2. We use images built in step 1 in the e2e tests.
3. When we push images, we push the images that we built in step 1 and tested in step 2.

- [ ] Build all images in repo
- [ ] Create basic e2e suite per provisioner
- [ ] Push images

**Comment by exdx** [comment]
Are we interested in building `quay.io/joelanford/kuberpak-unpack:v0.1.0` in this repository as well?

**Comment by timflannagan** [comment]
Somewhat related to this ticket as it doesn't seem like we have a ticket dedicated towards bootstrapping an e2e suite: https://github.com/operator-framework/rukpak/pull/80 added some basic e2e tests.

There's a couple of things missing from that PR:

- Basic BundleInstance e2e tests that ensure unpacked Bundle contents can be successfully applied on cluster
- The provisioner is deployed using standard Kubernetes manifests (vs. running as a background local process)
- Solidifying the e2e suite setup so local and CI environments can run the same Makefile targets
- We're hardcoding the unpack image used and we should aim towards using the CI built image when calling the provisioner binary

There's probably a good chunk of other things I'm missing as well, but I wanted to make a mental note while it's still fresh.

**Comment by timflannagan** [comment]
Combined the provisioner and unpack binaries into the same Dockerfile in #84 so we can deploy a single container image for the entire rukpak stack.

Follow-up to my previous comment yesterday: #85 adds a more streamlined e2e experience and builds on top of Dan's #82 PR so we can avoid running the provisioner binary in the background in CI.

**Comment by timflannagan** [comment]
#85 has merged and we're tracking pushing tags to the k8s-provisioner quay repository in https://github.com/operator-framework/rukpak/issues/91, so I'm going to close this out.
