### ISSUE TITLE
Add unit test coverage

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#59]
AC:

 - Meaningful unit test coverage of the code
 - e2e test covering the happy path(s)

Stretch:

- Add codecov tooling

**Comment by timflannagan** [comment]
Note: determine we can just add unit testing for the internal packages for now and hold off on testing the controller packages.

**Comment by akihikokuroda** [comment]
PR for internal/updater unit tests

**Comment by akihikokuroda** [comment]
PR for internal/helm-operator-plugins unit tests https://github.com/operator-framework/rukpak/pull/115

**Comment by exdx** [comment]
There was some consensus around breaking out the codecov work into a standalone ticket: https://github.com/operator-framework/rukpak/issues/196

**Comment by timflannagan** [comment]
Moving this out of the 0.4 milestone as our e2e suite is still pretty fleshed out at this point.

**Comment by tylerslaton** [comment]
Since we have pretty good coverage now and this issue has sat for awhile I'm going to go ahead and close this. In the future we can break whatever remaining unit tests that we want into separate issues or reopen this if we find it pertinent.
