### ISSUE TITLE
manifests location for a plain+v0 bundle

### ISSUE THREAD

**Issue by fgiloux** [operator-framework/rukpak#653]
According to [the API](https://github.com/operator-framework/rukpak/blob/main/api/v1alpha1/bundle_types.go#L80-L109)

- For an OCI image the manifests must be located at the root-level, i.e. /manifests directory for the provisioner to be able to locate the plain+v0 bundle.
- For a Git repo there is a field `directory` to specify the location.
- For a ConfigMap there is a field `path`to specify the location.

What is the rational for the differences? It seems that the UX may improve by having the location set in a consistent way across the three options, i.e:
- using the same name for the field,  `path` seems the more natural choice
- supporting the specification of the location for OCI images

**Comment by joelanford** [comment]
For an OCI image, the idea was that the image should only ever contain the bundle. We didn't want to encourage people to pack a whole bunch of extraneous stuff in an image because we have to ship that image around and unpack it to extract the bundle.

For a git repo, yes, `directory` lets you specify a subdirectory of the git root to extract. It looks like the code clones the repo and then returns a bundle FS rooted at the specified directory. Not sure if there's a way to avoid needing to pull the entire commit if we know we don't need a specific subdirectory. The idea here is that someone could point rukpak at a `directory: bundle` in a standard SDK project.

The `path` in configmap is a path to a specific directory within the bundle. In the `configmaps` case, all of the specified paths are rooted at the bundle root.

I think these are the correct choices, but at a minimum it seems like we should beef up the docs to explain things more. FWIW, I created #645 because we don't have _any_ docs right now for the configmaps source.

**Comment by joelanford** [comment]
> My point was why to call it directory for git and path for ConfigMaps?

Maybe the name can converge, but they do have different meanings, so converging them might actually increase confusion.
- `git` `directory` is the directory within the repo root that should be treated as the bundle root.
- `configmaps` `path` is the directory _within the bundle root_ where the configmap's data should be mounted as files.

**Comment by fgiloux** [comment]
This is indeed confusing. 

What benefits do you expect from mounting multiple ConfigMaps? It seems to go in the opposite direction of immutability.
Why does the mount point need to be exposed to users? Isn't it implementation internals of the plain provisioner? Especially if you don't want the bundle file structure to be configurable.
In the pod spec it is named `mountPath`.
~~~
ReadOnly bool `json:"readOnly,omitempty" protobuf:"varint,2,opt,name=readOnly"`
// Path within the container at which the volume should be mounted.  Must
// not contain ':'.
MountPath string `json:"mountPath" protobuf:"bytes,3,opt,name=mountPath"`
~~~

Nevertheless a directory is not a path. Does it mean that for git you would accept `/bundle` but not `/config/bundle`?

**Comment by fgiloux** [comment]
still relevant

**Comment by joelanford** [comment]
> What benefits do you expect from mounting multiple ConfigMaps?

To overcome the etcd size limit of a single configmap.

> Why does the mount point need to be exposed to users?

Different bundle formats have different requirements for where files need to exist relative to the bundle root. The ConfigMaps source is not specific to the plain provisioner.

**Comment by joelanford** [comment]
This design was inspired by the openshift build API: https://github.com/openshift/api/blob/8891815aa476232109dccf6c11b8611d209445d9/build/v1/types.go#L461-L463

**Comment by joelanford** [comment]
> It seems to go in the opposite direction of immutability.

Right now, for better or worse, there are validating webhooks in rukpak that ensure referenced config maps are immutable and cannot be deleted

**Comment by fgiloux** [comment]
> Different bundle formats have different requirements for where files need to exist relative to the bundle root. The ConfigMaps source is not specific to the plain provisioner.

Sorry I am not following why it needs to be exposed to users. I understand that for builds it matters as the Dockerfile, batch or whatever is used for the build and provided by the user needs to access the data.
For RukPak my understanding is that it is only internal code to the RukPak provisioners that accesses the content of the configmaps and applies it to Kubernetes. If different bundle formats have different requirements for where files need to exist relative to the bundle root can't the specific provisioners take care of it?

**Comment by ncdc** [comment]
I would like to see us have both sensible defaults for where we expect files to live inside a source, as well as allowing the user to change things if the defaults don't work for them.

I imagine we'll want to have a knob to configure the path in a source to consider its root; this is the "from".

We'll also want to have a knob to configure the path in the local staging area where the source's files go; this is the "to".

This is what we're working toward in #703

**Comment by fgiloux** [comment]
@ncdc #703 is surely moving us in the right direction. I am happy to close this and continue the discussion there.
