### ISSUE TITLE
manifests-diff CI workflow fails if PR branch has a / in its name

### ISSUE THREAD

**Issue by ncdc** [operator-framework/rukpak#667]
See e.g. https://github.com/operator-framework/rukpak/actions/runs/5729666108/job/15526872639?pr=666

```
mv: cannot move 'rukpak.yaml' to 'sre/cloud-ingress.yaml': No such file or directory
```

Branch name is `sre/cloud-ingress.yaml`

**Comment by joelanford** [comment]
This is also a problem for dependabot PRs.

**Comment by ncdc** [comment]
I see this was added in #640. I'd like to propose we remove this workflow instead of fixing it.

**Comment by ncdc** [comment]
@dtfranz

**Comment by dtfranz** [comment]
Agreed, created #679
