### ISSUE TITLE
Replace internal use of the Helm library to apply content with something else

### ISSUE THREAD

**Issue by ncdc** [operator-framework/rukpak#718]
When we use the Helm library to apply bundle content to the cluster, the Helm library creates a Helm Release behind the scenes, storing it in the cluster. This means a BundleDeployment is limited to the maximum amount allowed in a single etcd value, which is about 1.5MB.

We need to switch to something else that doesn't have this limitation. It could be something we build in-repo, such as a server-side-apply applier, or some other library.

**Comment by joelanford** [comment]
Closing. We are switching to direct use of Carvel's `kapp-controller`.
