### ISSUE TITLE
Document the plain manifest bundle format

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#75]
Goal: document the plain manifest bundle format and the required Dockerfile format.

Motivation: #71 introduces user documentation for interacting with the plain bundle provisioner, and we're missing the ability to link to documentation that acts as a source-of-truth for this bundle format.

**Comment by timflannagan** [comment]
Notes from PR reviews recently:

- It would be nice to have some static validation to ensure that the bundle format is consistent
- Document that the /manifests directory is where the k8s bundle provisioner expects the manifests to live
- #23 tracks investigating adding a package-level metadata file for this bundle format. we should work towards a consistent filesystem structure there as well + document what the provisioner expects to be present

**Comment by exdx** [comment]
WIP plain bundle spec doc: https://hackmd.io/jE5sIEc9TJWzN_u1rLpjZg

**Comment by timflannagan** [comment]
Note: we decide to house that bundle spec in the repository, and to link to that bundle spec in the nested plain provisioner README.md.
