### ISSUE TITLE
Passing context.Background() while setting up watches in BundleDeployment reconciler

### ISSUE THREAD

**Issue by varshaprasad96** [operator-framework/rukpak#799]
Currently, we pass the same context through `context.Background()` in handler funcs while setting up watches in the bundle deployment controller: https://github.com/operator-framework/rukpak/blob/1d284f91a3dfba176c1ff9e728e705681e885a25/internal/controllers/bundledeployment/bundledeployment.go#L114

`context.Background()` returns a non-cancellable, empty context, hence passing it to handler func is a no-op. 
A map function ideally runs and returns quickly. When using typed generated cache listers, you can traverse from the watch event to whatever you want from the listers without needing a context. But with controller-runtime's Client, you need to pass in a context (and you don't know if you're reading from the cache or using a live client unless you trace the creation of the client you're using).

Let's say instead of context.Background() here, you passed in some cancelable context. Because this call is creating a map function, whatever context you pass in is shared by all invocations of the map function. You can't easily cancel one without canceling all of them (although it's not really clear if we'd want to cancel just one).

Discussion: https://github.com/operator-framework/rukpak/pull/774#discussion_r1452725020

cc: @ncdc

**Comment by joelanford** [comment]
Fixed by #794
