### ISSUE TITLE
Rename the k8s provisioner to something more appropriate 

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#87]
Goal: rename the k8s provisioner to a more descriptive name.

Currently this provisioner operates on the plain Kubernetes manifest bundle format (which is still WIP) but the naming of this provisioner is still ambiguous without further context. We should try and iron out a better name before cutting an alpha release.

**Comment by timflannagan** [comment]
Note: we now have a quay.io/operator-framework/k8s-provisioner repository. We can garbage collect that repository if/when we change this provisioner name.

**Comment by timflannagan** [comment]
Note: sounds like we settled on renaming k8s -> plain and using the plain+v0 provisioner ID.

**Comment by exdx** [comment]
We made a quick consensus on plain+v0 as the bundle type and plainv0 as the provisioner name. This issue can be closed when the repo is updated to reflect the new provisioner ID.
