### ISSUE TITLE
Create a slack channel in the Kubernetes workspace for rukpak

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#95]
Goal: investigate if we can create a standalone #rukpak-dev channel in the Kubernetes slack channel. The rukpak component is a sub-project of the overall operator-framework CNCF project.

**Comment by timflannagan** [comment]
cc @joelanford as it sounded like you had an idea on how to do this (if it's even possible).

**Comment by timflannagan** [comment]
This can probably be moved to the 0.2 milestone when we're grooming the 0.1 milestone for any blocking issues.

**Comment by joelanford** [comment]
Example here: https://github.com/kubernetes/community/pull/4978

**Comment by joelanford** [comment]
Done. See https://github.com/kubernetes/community/pull/6564
