### ISSUE TITLE
Create a rukpak WG under the OLM project umbrella

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#97]
Investigate whether we should create a sub-WG under OLM's project umbrella that's dedicated towards the rukpak component.

It looks like this is already possible looking at the WG's listed in the [o-f/community repository])https://github.com/operator-framework/community) and could help prevent the standard OLM WG meetings from being more cluttered with topics over time.

**Comment by exdx** [comment]
I'm not super convinced that this is the direction we should take soon. If we look at rukpak as OLM v2, and we answer issues in the community with "we will fix this in the new APIs", referring to v2, then I think it's ok to discuss rukpak and v2 issues in our existing community. If in some meeting we discuss mainly the new APIs and projects like rukpak and depster then I think that's fine.

It's also worth noting that our active community is really small at the moment, there's no need to fragment it. Maybe once we have a large base of rukpak users, and it becomes apparent rukpak is its own community, then maybe the separate wg will naturally make sense.

**Comment by timflannagan** [comment]
Yep - definitely agree with the current state of the project. In any case, it still felt worth creating a tracking ticket while we continue to iterate upstream.
